let goods = [
    {
        pic:'',
        title:'椰云拿铁',
        desc:`一人份【年度重磅，一口吞云】`,
        sellNumber:200,
        favorRate:95,
        price:32
    },
    {
        pic:'',
        title:'椰云拿铁',
        desc:`一人份【年度重磅，一口吞云】`,
        sellNumber:200,
        favorRate:95,
        price:32
    },
    {
        pic:'',
        title:'生椰拿铁',
        desc:`一人份【年度重磅，一口吞云】`,
        sellNumber:200,
        favorRate:95,
        price:19
    },
    {
        pic:'',
        title:'椰云拿铁',
        desc:`一人份【年度重磅，一口吞云】`,
        sellNumber:200,
        favorRate:95,
        price:32
    },
    {
        pic:'',
        title:'椰云拿铁',
        desc:`一人份【年度重磅，一口吞云】`,
        sellNumber:200,
        favorRate:95,
        price:32
    },

]